version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - sqlite_data:/app/db
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env.development
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - scm_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - scm_network
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - backend
    networks:
      - scm_network
    restart: unless-stopped

networks:
  scm_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  sqlite_data:
