# Generated by Django 4.2.11 on 2025-03-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("materials", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("issue", "Issue"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                        verbose_name="Transaction Type",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Quantity"
                    ),
                ),
                (
                    "is_general_use",
                    models.BooleanField(default=False, verbose_name="Is General Use"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transactions",
                        to="inventory.warehouse",
                        verbose_name="From Warehouse",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "purchase_order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="procurement.purchaseorderitem",
                        verbose_name="Purchase Order Item",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transactions",
                        to="inventory.warehouse",
                        verbose_name="To Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Transaction",
                "verbose_name_plural": "Inventory Transactions",
            },
        ),
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="inventory.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Location",
                "verbose_name_plural": "Inventory Locations",
                "unique_together": {("warehouse", "code")},
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Minimum Quantity",
                    ),
                ),
                (
                    "monitor_stock_level",
                    models.BooleanField(
                        default=False, verbose_name="Monitor Stock Level"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_items",
                        to="inventory.inventorylocation",
                        verbose_name="Location",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="materials.material",
                        verbose_name="Material",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="inventory.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "unique_together": {("material", "warehouse", "location")},
            },
        ),
    ]
