# Generated by Django 4.2.9 on 2025-03-25 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterModelTable(
            name="department",
            table="departments",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Permission name", max_length=100, verbose_name="Name"
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        help_text="Unique permission identifier",
                        max_length=100,
                        unique=True,
                        verbose_name="Codename",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                        verbose_name="Description",
                    ),
                ),
                (
                    "is_basic",
                    models.BooleanField(
                        default=False,
                        help_text="If True, all users in the department get this permission",
                        verbose_name="Is Basic Permission",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department this permission belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="accounts.department",
                        verbose_name="Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "indexes": [
                    models.Index(
                        fields=["codename"], name="permissions_codenam_5f0327_idx"
                    ),
                    models.Index(
                        fields=["department", "is_basic"],
                        name="permissions_departm_62dba5_idx",
                    ),
                ],
            },
        ),
    ]
