# Generated by Django 4.2.11 on 2025-03-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Unit Price"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Total Price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRR", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "set_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Set Date"),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved Date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Accounting Entry",
                "verbose_name_plural": "Accounting Entries",
            },
        ),
        migrations.CreateModel(
            name="GeneralExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="Expense Date")),
                (
                    "allocation_type",
                    models.CharField(
                        choices=[
                            ("project_specific", "Project Specific"),
                            ("weight_based", "Weight Based"),
                        ],
                        max_length=20,
                        verbose_name="Allocation Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Expense",
                "verbose_name_plural": "General Expenses",
            },
        ),
        migrations.CreateModel(
            name="ProjectIncome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Amount"
                    ),
                ),
                ("income_date", models.DateField(verbose_name="Income Date")),
            ],
            options={
                "verbose_name": "Project Income",
                "verbose_name_plural": "Project Incomes",
            },
        ),
    ]
