# Generated by Django 4.2.9 on 2025-03-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="accountingentry",
            table="accounting_entry",
        ),
        migrations.AlterModelTable(
            name="generalexpense",
            table="general_expense",
        ),
        migrations.AlterModelTable(
            name="projectincome",
            table="project_income",
        ),
    ]
