# Generated by Django 4.2.9 on 2025-03-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="requestitem",
            table="request_items",
        ),
        migrations.AlterModelTable(
            name="requestlist",
            table="request_lists",
        ),
    ]
