# Generated by Django 4.2.9 on 2025-03-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["name"],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.AlterModelTable(
            name="purchaseorder",
            table="purchase_orders",
        ),
        migrations.AlterModelTable(
            name="purchaseorderitem",
            table="purchase_order_items",
        ),
        migrations.AlterModelTable(
            name="supplier",
            table="suppliers",
        ),
    ]
